name: view_template
description: An absolute bare-bones web app with view library.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  view:
    git:
      url: https://github.com/bryanbill/view

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
